version: '3'

services:
  db:
    image: postgres:10.3-alpine
    env_file: gallery.env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  django:
    build:
      context: "./photogallery"
      args:
        SIMD_LEVEL: "avx2"
    restart: always
    command: sh -c "/gallery/start.sh"
    volumes:
      - ./photogallery/:/gallery
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
    env_file: gallery.env

  redis:
    image: redis:4-alpine
    restart: always
    env_file: gallery.env
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  celery:
    build:
      context: "./photogallery"
      args:
        SIMD_LEVEL: "avx2"
    restart: always
    command: sh -c "nice -n19 ionice -c3 celery -A photogallery worker --loglevel=info"
    volumes:
      - ./photogallery/:/gallery
    depends_on:
      - db
      - redis
    env_file: gallery.env

volumes:
  db:
  redis:
