version: '3'

services:
  db:
    image: postgres:9.6-alpine
    env_file: env.conf
    ports:
     - "5432:5432"
  django:
    build:
      context: "./photogallery"
      args:
        SIMD_LEVEL: "sse4"
    command: sh -c "/gallery/start.sh"
    volumes:
      - ./photogallery/:/gallery
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: env.conf
