version: '3'

services:
  db:
    image: postgres:10.2-alpine
    env_file: gallery.env
    ports:
      - "5432:5432"
  django:
    build:
      context: "./photogallery"
      args:
        SIMD_LEVEL: "avx2"
    restart: on-failure:5
    command: sh -c "/gallery/start.sh"
    volumes:
      - ./photogallery/:/gallery
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: gallery.env
