# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_album', models.PositiveIntegerField(null=True, verbose_name='Parent album')),
                ('title', models.CharField(max_length=255, verbose_name='Directory')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('directory', models.SlugField(verbose_name='Slug')),
                ('album_cover', models.CharField(max_length=255, verbose_name='Album cover')),
                ('sort_order', models.CharField(max_length=255, null=True, verbose_name='Sort order')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='test/', verbose_name='Image file')),
                ('file_hash', models.CharField(max_length=255, null=True, verbose_name='SHA-256')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Album')),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
    ]
