# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, validators=[gallery.models.validate_album_title], verbose_name='Title')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('directory', models.SlugField(unique=True, verbose_name='Directory')),
                ('sort_order', models.CharField(blank=True, choices=[('date', 'Date (ascending'), ('-date', 'Date (descending)'), ('title', 'Title (ascending)'), ('-title', 'Title (descending)')], help_text='Sort order of photos in this album', max_length=255, verbose_name='Sort order')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('image', models.ImageField(upload_to=gallery.models.Photo.upload_dir, verbose_name='Image file')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file_hash', models.CharField(blank=True, max_length=255, verbose_name='SHA-256')),
                ('preview_img', models.ImageField(blank=True, upload_to='', verbose_name='Preview image')),
                ('hidpi_preview_img', models.ImageField(blank=True, upload_to='', verbose_name='High DPI preview image')),
                ('thumbnail_img', models.ImageField(blank=True, upload_to='', verbose_name='Thumbnail image')),
                ('hidpi_thumbnail_img', models.ImageField(blank=True, upload_to='', verbose_name='High DPI thumbnail image')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.Album')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Photo', to='gallery.Photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subalbums', to='gallery.Album'),
        ),
    ]
