# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='album',
            name='parent_album',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Parent album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='sort_order',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SHA-256'),
        ),
    ]
