# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='sort_order',
            field=models.CharField(choices=[('date', 'Date (ascending'), ('-date', 'Date (descending)'), ('title', 'Title (ascending)'), ('-title', 'Title (descending)')], default='title', help_text='Sort order of photos in this album', max_length=255, verbose_name='Sort order'),
        ),
    ]
