# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 13:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170208_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Photo', to='gallery.Photo', verbose_name='Album cover'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='album',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subalbums', to='gallery.Album', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='album',
            name='sort_order',
            field=models.CharField(choices=[('date', 'Date (ascending)'), ('-date', 'Date (descending)'), ('title', 'Title (ascending)'), ('-title', 'Title (descending)')], default='title', help_text='Sort order of photos in this album', max_length=255, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.Album', verbose_name='Album'),
        ),
    ]
