# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170501_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ready',
            field=models.BooleanField(default=True, verbose_name='Ready'),
        ),
    ]
