# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20160517_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='hidden',
        ),
        migrations.AddField(
            model_name='album',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
    ]
