# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160517_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='directory',
            field=models.SlugField(verbose_name='Directory'),
        ),
    ]
