# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20170915_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='hidpi_preview_img',
            field=models.ImageField(blank=True, max_length=150, upload_to='', verbose_name='High DPI preview image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='hidpi_thumbnail_img',
            field=models.ImageField(blank=True, max_length=150, upload_to='', verbose_name='High DPI thumbnail image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='preview_img',
            field=models.ImageField(blank=True, max_length=150, upload_to='', verbose_name='Preview image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail_img',
            field=models.ImageField(blank=True, max_length=150, upload_to='', verbose_name='Thumbnail image'),
        ),
    ]
