# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20170924_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='downloadable',
            field=models.BooleanField(default=False, verbose_name='Downloads allowed'),
        ),
    ]
