# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_album_downloadable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='downloadable',
            field=models.BooleanField(default=False, verbose_name='ZIP downloads allowed'),
        ),
    ]
