# Generated by Django 2.0.2 on 2018-02-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20180211_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exifdata',
            options={'verbose_name': 'EXIF data', 'verbose_name_plural': 'EXIF data'},
        ),
    ]
