# Generated by Django 2.0.2 on 2018-02-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_auto_20180213_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exifdata',
            options={'ordering': ('-date_taken',), 'verbose_name': 'EXIF data', 'verbose_name_plural': 'EXIF data'},
        ),
    ]
