# Generated by Django 2.0.2 on 2018-02-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_auto_20180213_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exifdata',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gallery.Photo', verbose_name='Photo'),
        ),
    ]
