# Generated by Django 2.0.2 on 2018-02-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_auto_20180213_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='exifdata',
            name='area',
            field=models.CharField(max_length=200, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='exifdata',
            name='country',
            field=models.CharField(max_length=200, null=True, verbose_name='Country'),
        ),
    ]
