# Generated by Django 2.0.2 on 2018-02-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_auto_20180214_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exifdata',
            old_name='area',
            new_name='locality',
        ),
    ]
