# Generated by Django 2.0.2 on 2018-02-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_auto_20180215_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exifdata',
            name='locality',
            field=models.CharField(max_length=200, null=True, verbose_name='Locality'),
        ),
    ]
