# Generated by Django 2.0.1 on 2018-02-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_auto_20180215_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exifdata',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Locality'),
            preserve_default=False,
        ),
    ]
