# Generated by Django 2.0.1 on 2018-02-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0026_auto_20180215_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exifdata',
            name='make',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Manufacturer'),
            preserve_default=False,
        ),
    ]
