# Generated by Django 2.0.1 on 2018-02-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0029_auto_20180216_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exifdata',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Country'),
        ),
    ]
