# Generated by Django 2.0.1 on 2018-02-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0030_auto_20180216_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exifdata',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='exifdata',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='exifdata',
            name='shutter_speed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Shutter speed'),
        ),
    ]
