# Generated by Django 2.0.2 on 2018-02-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0031_auto_20180216_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='show_location',
            field=models.BooleanField(default=True, verbose_name='Show location information'),
        ),
        migrations.AddField(
            model_name='album',
            name='show_metadata',
            field=models.BooleanField(default=True, verbose_name='Show EXIF metadata'),
        ),
        migrations.AlterField(
            model_name='album',
            name='downloadable',
            field=models.BooleanField(default=False, verbose_name='Allow ZIP download'),
        ),
    ]
