# Generated by Django 2.0.2 on 2018-03-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0032_auto_20180216_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exifdata',
            name='altitude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altitude'),
        ),
    ]
